import type { StackProfile, ToolOutput } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateAider(profile: StackProfile): ToolOutput {
  const rules = buildRuleSet(profile);
  const header = `# Conventions\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  const content = renderMarkdownRules(rules, header);

  return {
    toolId: "aider",
    toolName: "Aider",
    filePath: "CONVENTIONS.md",
    content,
  };
}
