import type { StackProfile, ToolOutput, RuleSet, RuleMode } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateAmazonQ(profile: StackProfile, customRules?: RuleSet, mode?: RuleMode): ToolOutput {
  const rules = buildRuleSet(profile, customRules, mode);
  const header = `# Amazon Q Rules\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  return { toolId: "amazonq", toolName: "Amazon Q", filePath: ".amazonq/rules/onerules.md", content: renderMarkdownRules(rules, header) };
}
