import type { StackProfile, ToolOutput, RuleSet, RuleMode } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateAugment(profile: StackProfile, customRules?: RuleSet, mode?: RuleMode): ToolOutput {
  const rules = buildRuleSet(profile, customRules, mode);
  const header = `# Augment Code Guidelines\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  return { toolId: "augment", toolName: "Augment Code", filePath: ".augment-guidelines", content: renderMarkdownRules(rules, header) };
}
