import type { StackProfile, ToolOutput, RuleSet, RuleMode } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateBolt(profile: StackProfile, customRules?: RuleSet, mode?: RuleMode): ToolOutput {
  const rules = buildRuleSet(profile, customRules, mode);
  const header = `# Bolt Rules\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  return { toolId: "bolt", toolName: "Bolt.new", filePath: ".boltrules", content: renderMarkdownRules(rules, header) };
}
