import type { StackProfile, ToolOutput, RuleSet } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateClaude(profile: StackProfile): ToolOutput {
  const rules = buildRuleSet(profile);
  const header = `# Project Rules\n\n> Generated by [onerules](https://github.com/onerules/onerules) — ${formatStackSummary(profile)}`;
  const content = renderMarkdownRules(rules, header);

  return {
    toolId: "claude",
    toolName: "Claude Code",
    filePath: "CLAUDE.md",
    content,
  };
}
