import type { StackProfile, ToolOutput, RuleSet } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateCodex(profile: StackProfile, customRules?: RuleSet): ToolOutput {
  const rules = buildRuleSet(profile, customRules);
  const header = `# Agent Rules\n\n> ${formatStackSummary(profile)} — generated by [onerules](https://github.com/onerules/onerules)`;
  const content = renderMarkdownRules(rules, header);

  return {
    toolId: "codex",
    toolName: "OpenAI Codex",
    filePath: "AGENTS.md",
    content,
  };
}
