import type { StackProfile, ToolOutput } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateCodex(profile: StackProfile): ToolOutput {
  const rules = buildRuleSet(profile);
  const header = `# Agent Rules\n\n> ${formatStackSummary(profile)} — generated by [onerules](https://github.com/onerules/onerules)`;
  const content = renderMarkdownRules(rules, header);

  return {
    toolId: "codex",
    toolName: "OpenAI Codex",
    filePath: "AGENTS.md",
    content,
  };
}
