import type { StackProfile, ToolOutput, RuleSet } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateCopilot(profile: StackProfile, customRules?: RuleSet): ToolOutput {
  const rules = buildRuleSet(profile, customRules);
  const header = `# Copilot Instructions\n\n> ${formatStackSummary(profile)} — generated by [onerules](https://github.com/onerules/onerules)`;
  const content = renderMarkdownRules(rules, header);

  return {
    toolId: "copilot",
    toolName: "GitHub Copilot",
    filePath: ".github/copilot-instructions.md",
    content,
  };
}
