import type { StackProfile, ToolOutput, RuleSet, RuleMode } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateCursor(profile: StackProfile, customRules?: RuleSet, mode?: RuleMode): ToolOutput {
  const rules = buildRuleSet(profile, customRules, mode);

  const frontmatter = [
    "---",
    "description: Project coding rules generated by onerules",
    "globs:",
    "alwaysApply: true",
    "---",
    "",
  ].join("\n");

  const header = `# Project Rules\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  const content = frontmatter + renderMarkdownRules(rules, header);

  return {
    toolId: "cursor",
    toolName: "Cursor",
    filePath: ".cursor/rules/onerules.mdc",
    content,
  };
}
