import type { StackProfile, ToolOutput, RuleSet, RuleMode } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateGemini(profile: StackProfile, customRules?: RuleSet, mode?: RuleMode): ToolOutput {
  const rules = buildRuleSet(profile, customRules, mode);
  const header = `# Project Rules\n\n> ${formatStackSummary(profile)} — generated by [onerules](https://github.com/onerules/onerules)`;
  const content = renderMarkdownRules(rules, header);

  return {
    toolId: "gemini",
    toolName: "Gemini CLI",
    filePath: "GEMINI.md",
    content,
  };
}
