import type { StackProfile, ToolOutput, RuleSet, RuleMode } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateGoose(profile: StackProfile, customRules?: RuleSet, mode?: RuleMode): ToolOutput {
  const rules = buildRuleSet(profile, customRules, mode);
  const header = `# Goose Hints\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  return { toolId: "goose", toolName: "Goose", filePath: ".goosehints", content: renderMarkdownRules(rules, header) };
}
