import type { StackProfile, ToolOutput, RuleSet, RuleMode } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateJunie(profile: StackProfile, customRules?: RuleSet, mode?: RuleMode): ToolOutput {
  const rules = buildRuleSet(profile, customRules, mode);
  const header = `# Junie Guidelines\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  return { toolId: "junie", toolName: "JetBrains Junie", filePath: ".junie/guidelines.md", content: renderMarkdownRules(rules, header) };
}
