import type { StackProfile, ToolOutput, RuleSet } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateKiro(profile: StackProfile, customRules?: RuleSet): ToolOutput {
  const rules = buildRuleSet(profile, customRules);
  const header = `# Kiro Rules\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  const content = renderMarkdownRules(rules, header);

  return {
    toolId: "kiro",
    toolName: "Kiro",
    filePath: ".kiro/rules/onerules.md",
    content,
  };
}
