import type { StackProfile, ToolOutput, RuleSet, RuleMode } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateKiro(profile: StackProfile, customRules?: RuleSet, mode?: RuleMode): ToolOutput {
  const rules = buildRuleSet(profile, customRules, mode);
  const header = `# Kiro Rules\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  const content = renderMarkdownRules(rules, header);

  return {
    toolId: "kiro",
    toolName: "Kiro",
    filePath: ".kiro/rules/onerules.md",
    content,
  };
}
