import type { StackProfile, ToolOutput, RuleSet, RuleMode } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateRoo(profile: StackProfile, customRules?: RuleSet, mode?: RuleMode): ToolOutput {
  const rules = buildRuleSet(profile, customRules, mode);
  const header = `# Roo Code Rules\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  const content = renderMarkdownRules(rules, header);

  return {
    toolId: "roo",
    toolName: "Roo Code",
    filePath: ".roo/rules/onerules.md",
    content,
  };
}
