import type { StackProfile, ToolOutput, RuleSet, RuleMode } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateTrae(profile: StackProfile, customRules?: RuleSet, mode?: RuleMode): ToolOutput {
  const rules = buildRuleSet(profile, customRules, mode);
  const header = `# Trae Rules\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  const content = renderMarkdownRules(rules, header);

  return {
    toolId: "trae",
    toolName: "Trae",
    filePath: ".trae/rules/onerules.md",
    content,
  };
}
