import type { StackProfile, ToolOutput, RuleSet, RuleMode } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateVoid(profile: StackProfile, customRules?: RuleSet, mode?: RuleMode): ToolOutput {
  const rules = buildRuleSet(profile, customRules, mode);
  const header = `# Void Rules\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  return { toolId: "void", toolName: "Void", filePath: ".voidrules", content: renderMarkdownRules(rules, header) };
}
