import type { StackProfile, ToolOutput, RuleSet, RuleMode } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateWarp(profile: StackProfile, customRules?: RuleSet, mode?: RuleMode): ToolOutput {
  const rules = buildRuleSet(profile, customRules, mode);
  const header = `# Warp Rules\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  return { toolId: "warp", toolName: "Warp Terminal", filePath: "WARP.md", content: renderMarkdownRules(rules, header) };
}
