import type { StackProfile, ToolOutput, RuleSet } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateWindsurf(profile: StackProfile, customRules?: RuleSet): ToolOutput {
  const rules = buildRuleSet(profile, customRules);
  const header = `# Windsurf Rules\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  const content = renderMarkdownRules(rules, header);

  return {
    toolId: "windsurf",
    toolName: "Windsurf",
    filePath: ".windsurfrules",
    content,
  };
}
