import type { StackProfile, ToolOutput, RuleSet, RuleMode } from "../types.js";
import { buildRuleSet, renderMarkdownRules, formatStackSummary } from "./common.js";

export function generateZed(profile: StackProfile, customRules?: RuleSet, mode?: RuleMode): ToolOutput {
  const rules = buildRuleSet(profile, customRules, mode);
  const header = `# Zed AI Rules\n\n> ${formatStackSummary(profile)} — generated by onerules`;
  return { toolId: "zed", toolName: "Zed AI", filePath: ".rules", content: renderMarkdownRules(rules, header) };
}
