import { readFile, readdir, stat } from "node:fs/promises";
import { join, extname } from "node:path";
import type { StackProfile } from "../types.js";
import { formatStackSummary } from "../generate/common.js";

const IGNORE_DIRS = new Set([
  "node_modules", ".git", "dist", "build", ".next", ".nuxt",
  "__pycache__", ".venv", "venv", "target", "vendor",
  ".turbo", ".cache", "coverage",
]);

export async function generateAIPrompt(dir: string, profile: StackProfile): Promise<string> {
  const fileTree = await buildFileTree(dir, "", 3);
  const stackSummary = formatStackSummary(profile);

  let existingRules = "";
  try {
    existingRules = await readFile(join(dir, "CLAUDE.md"), "utf-8");
  } catch {}

  const sections: string[] = [
    `# Generate Project-Specific Coding Rules`,
    ``,
    `You are analyzing a codebase to generate project-specific coding rules. These rules will be saved to CLAUDE.md (or equivalent) and used by AI coding tools.`,
    ``,
    `## Detected Stack`,
    ``,
    `- **Stack:** ${stackSummary}`,
    `- **Languages:** ${profile.languages.join(", ")}`,
    `- **Framework:** ${profile.framework || "none"}`,
    `- **Libraries:** ${profile.libraries.join(", ") || "none"}`,
    `- **Package manager:** ${profile.packageManager || "unknown"}`,
    `- **Test framework:** ${profile.testFramework || "none"}`,
    `- **Linter:** ${profile.linter || "none"}`,
    `- **CI:** ${profile.ci || "none"}`,
    ``,
    `## File Structure`,
    ``,
    "```",
    fileTree,
    "```",
    ``,
  ];

  if (existingRules) {
    sections.push(
      `## Existing Rules (CLAUDE.md)`,
      ``,
      "```markdown",
      existingRules,
      "```",
      ``,
    );
  }

  sections.push(
    `## Your Task`,
    ``,
    `Analyze this codebase and generate **project-specific** coding rules. These should NOT be generic best practices — they should reference THIS project's actual:`,
    ``,
    `1. **Architecture patterns** — how is this project structured? What patterns does it use? (e.g., "The \`src/engine/\` directory uses the Strategy pattern — new strategies must implement the interface in \`src/engine/types.ts\`")`,
    `2. **File conventions** — how are files organized? What naming patterns exist? (e.g., "API routes live in \`src/routes/\` and follow the \`{resource}.routes.ts\` naming convention")`,
    `3. **Data flow** — how does data move through the system? (e.g., "All database mutations go through service functions in \`src/services/\`, never directly from route handlers")`,
    `4. **Anti-patterns specific to THIS project** — what mistakes would a new contributor (human or AI) make? (e.g., "DO NOT import from \`src/legacy/\` — those modules are deprecated and being migrated")`,
    `5. **Domain-specific rules** — what does someone need to know about the business domain? (e.g., "All monetary values are stored as integers in cents. Never use floating point for money.")`,
    ``,
    `## Output Format`,
    ``,
    `Output ONLY the rules in this markdown format. No explanation, no preamble:`,
    ``,
    "```markdown",
    `## Project-Specific Rules`,
    ``,
    `> Auto-generated by onerules ai — review and edit as needed.`,
    ``,
    `### Architecture`,
    `- [rule referencing actual project structure]`,
    ``,
    `### Conventions`,
    `- [rule referencing actual file/naming patterns]`,
    ``,
    `### Do Not`,
    `- DO NOT [project-specific anti-pattern]`,
    ``,
    `### Domain`,
    `- [business-domain rule]`,
    "```",
    ``,
    `Generate 15-30 rules. Each rule must reference a specific file, directory, pattern, or convention that exists in THIS project. Generic rules like "write clean code" are worthless — be specific.`,
  );

  return sections.join("\n");
}

async function buildFileTree(dir: string, prefix: string, maxDepth: number): Promise<string> {
  if (maxDepth <= 0) return prefix + "...";
  const lines: string[] = [];

  try {
    const entries = await readdir(dir);
    const sorted = entries
      .filter((e) => !e.startsWith(".") && !IGNORE_DIRS.has(e))
      .sort();

    for (const entry of sorted.slice(0, 30)) {
      const fullPath = join(dir, entry);
      const s = await stat(fullPath).catch(() => null);
      if (!s) continue;

      if (s.isDirectory()) {
        lines.push(`${prefix}${entry}/`);
        const sub = await buildFileTree(fullPath, prefix + "  ", maxDepth - 1);
        if (sub) lines.push(sub);
      } else {
        lines.push(`${prefix}${entry}`);
      }
    }

    if (sorted.length > 30) {
      lines.push(`${prefix}... (${sorted.length - 30} more files)`);
    }
  } catch {}

  return lines.join("\n");
}
